apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  HAZELCAST_SERVICE: "hazelcast"
  HAZELCAST_PORT: "5701"
  QUEUE_NAME: "counter-queue"
  LOGGING_SERVICE_NAME: "logging-service"
  LOGGING_SERVICE_PORT: "5001"
  COUNTER_SERVICE_NAME: "counter-service"
  COUNTER_SERVICE_PORT: "5002"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "bankdb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"