apiVersion: apps/v1
kind: Deployment
metadata:
  name: facade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facade-service
  template:
    metadata:
      labels:
        app: facade-service
    spec:
      serviceAccountName: app-discovery-sa
      containers:
        - name: facade-service
          image: facade-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: facade-service
spec:
  type: NodePort
  selector:
    app: facade-service
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007