apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-discovery-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-discovery-role
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-discovery-rolebinding
subjects:
  - kind: ServiceAccount
    name: app-discovery-sa
roleRef:
  kind: Role
  name: app-discovery-role
  apiGroup: rbac.authorization.k8s.io
